@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.gear.traits;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;